openapi: 3.0.0
info:
  title: MFA API
  description: API for MFA authentication
  version: 1.0.0
servers:
  - url: http://localhost:3000/api/v1
paths:
  /mfa/qrcode:
    get:
      summary: Get QR Code for MFA
      security:
        - jwtAuth: []
      responses:
        '200':
          description: OK
        '401':
          description: Unauthorized
        '426':
          description: Upgrade Required
      operationId: getQrCode
    post:
      summary: Verify MFA token and get access and refresh tokens
      security:
        - jwtAuth: []
      responses:
        '200':
          description: OK
        '401':
          description: Unauthorized
        '426':
          description: Upgrade Required
      operationId: verifyMfaToken
  components:
    securitySchemes:
      jwtAuth:
        type: http
        scheme: bearer
        bearerFormat: JWT
