openapi: 3.0.0
info:
  version: 1.0.0
  title: ExpressJS with Passport JWT and MFA
servers:
  - url: http://localhost:3000/
paths:
  /open:
    get:
      summary: Open route
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: This route is open
    security:
      - []

  /protected:
    get:
      summary: Protected route
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: This route is protected
                  user:
                    type: object
                    properties:
                      id:
                        type: string
                        example: 123
                      email:
                        type: string
                        example: example@email.com
                      mfaValid:
                        type: boolean
                        example: true
        403:
          description: Forbidden
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Forbidden: make sure you MFA with Google Authenticator"
    security:
      - JWT: []

components:
  securitySchemes:
    JWT:
      type: http
      scheme: bearer
      bearerFormat: JWT