swagger: "2.0"
info:
  version: "1.0.0"
  title: Authentication API
  description: Authentication API using Passport.js and JWT
basePath: "/api/v1"
tags:
  - name: authentication
    description: Operations related to authentication
schemes:
  - http
paths:
  /register:
    post:
      tags:
        - authentication
      summary: Register a new user
      description: Registers a new user and generates a MFA token
      produces:
        - application/json
      parameters:
        - name: email
          in: body
          required: true
          schema:
            type: object
            properties:
              email:
                type: string
              password:
                type: string
            required:
              - email
              - password
      responses:
        200:
          description: OK
          schema:
            type: object
            properties:
              mfaToken:
                type: string
        409:
          description: Conflict
          schema:
            type: object
            properties:
              message:
                type: string
        500:
          description: Internal Server Error
          schema:
            type: object
            properties:
              message:
                type: string
  /login:
    post:
      tags:
        - authentication
      summary: Login a user
      description: Logs in a user and generates a MFA token
      produces:
        - application/json
      parameters:
        - name: email
          in: body
          required: true
          schema:
            type: object
            properties:
              email:
                type: string
              password:
                type: string
            required:
              - email
              - password
      responses:
        200:
          description: OK
          schema:
            type: object
            properties:
              mfaToken:
                type: string
        401:
          description: Unauthorized
          schema:
            type: object
            properties:
              message:
                type: string
        500:
          description: Internal Server Error
          schema:
            type: object
            properties:
              message:
                type: string
  /logout:
    get:
      tags:
        - authentication
      summary: Logout a user
      description: Logs out a user
      produces:
        - application/json
      security:
        - BearerAuth: []
      responses:
        404:
          description: Not Found
          schema:
            type: object
            properties:
              message:
                type: string
        500:
          description: Internal Server Error
          schema:
            type: object
            properties:
              message:
                type: string
  /refresh:
    get:
      tags:
        - authentication
      summary: Refresh access token
      description: Refreshes the access token of a user
      produces:
        - application/json
      security:
        - BearerRefreshAuth: []
      responses:
        200:
          description: OK
          schema:
            type: object
            properties:
              accessToken:
                type: string
              refreshToken:
                type: string
        401:
          description: Unauthorized
          schema:
            type: object
            properties:
              message:
                type: string
        426:
          description: Upgrade Required
          schema:
            type: object
            properties:
              message:
                type: string
        500:
          description: Internal Server Error
          schema:
            type: object
            properties:
              error:
                type: string
securityDefinitions:
  BearerAuth:
    type: apiKey
    in: header
